# coding=utf-8

from __future__ import unicode_literals

from httplib import RESET_CONTENT, BAD_REQUEST, NO_CONTENT


STATUS_AJAXY_REDIRECT = 231
STATUS_AJAXY_INLINE_REDIRECT = 232
STATUS_AJAXY_NO_OPERATION = NO_CONTENT
STATUS_AJAXY_RELOAD = RESET_CONTENT
STATUS_AJAXY_BAD_REQUEST = BAD_REQUEST
